cd ..
cd include/raylib/src
make PLATFORM=PLATFORM_DESKTOP CUSTOM_CFLAGS+="-DSUPPORT_FILEFORMAT_BMP -DSUPPORT_FILEFORMAT_TGA -DSUPPORT_FILEFORMAT_JPG -DSUPPORT_FILEFORMAT_PSD -DSUPPORT_FILEFORMAT_HDR -DSUPPORT_FILEFORMAT_PIC -DSUPPORT_FILEFORMAT_KTX -DSUPPORT_FILEFORMAT_ASTC -DSUPPORT_FILEFORMAT_PKM -DSUPPORT_FILEFORMAT_PVR -DSUPPORT_FILEFORMAT_SVG" -B

cd ../../meshoptimizer
mkdir build
cd build
cmake .. -G "MinGW Makefiles"
make

cd ../../ffmpeg/libavutil
setlocal

set "file=avconfig.h"

if not exist "%file%" (
    echo /* Generated by ffconf */ > "%file%"
    echo #ifndef AVUTIL_AVCONFIG_H >> "%file%"
    echo #define AVUTIL_AVCONFIG_H >> "%file%"
    echo #define AV_HAVE_BIGENDIAN 0 >> "%file%"
    echo #define AV_HAVE_FAST_UNALIGNED 0 >> "%file%"
    echo #endif /* AVUTIL_AVCONFIG_H */ >> "%file%"
)

endlocal