name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive  # Ensure all submodules are initialized

      - name: Install dependencies
        run: |
          chmod +x Install/install.sh Install/build_dependencies.sh
          ./Install/install.sh
          ./Install/build_dependencies.sh

      - name: Build Engine
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)
