name: CI Pipeline

on: [push, pull_request]

jobs:
  # ──────────── LINUX BUILD ────────────
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout submodules
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Install dependencies (Linux)
        run: |
          chmod +x Install/install.sh
          ./Install/install.sh

      - name: Build Engine (Linux)
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

  # ──────────── WINDOWS BUILD ────────────
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Install dependencies (Windows)
        shell: pwsh
        run: |
          cd Install
          .\install.bat

      - name: Build Engine (Windows)
        shell: pwsh
        run: |
          mkdir build
          cd build

          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release